class FDRlocators {

FDR_TAB = ()=> cy.get('#nav > ul:nth-child(1) > li.dropdown.open > ul > li:nth-child(2) > a')
FDR_TOMORROW1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(3) > select')
FDR_TOMORROW2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(3) > select')
FDR_TOMORROW3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(3) > select')
FDR_TOMORROW4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(3) > select')
FDR_TOMORROW5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(3) > select')
FDR_TOBANTOMMOROW1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive') 
FDR_TOBANTOMMOROW2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive')  
FDR_TOBANTOMMOROW3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive') 
FDR_TOBANTOMMOROW4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive') 
FDR_TOBANTOMMOROW5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive') 
FDR_SAVEBTTN = ()=> cy.get('#saverButton[type="button"]')
FDR_ALERTSUCCESS = ()=> cy.get('#modal > div.modal-header > h3')
FDR_ALERTSUCCESSNOTE = ()=> cy.get('#modal > div.modal-body > p') 
FDR_ALERTSUCCESSCLOSE = ()=> cy.get('#OK[class="btn"]')
FDR_TOBANTOMORROWASSERT1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FDR_TOBANTOMORROWASSERT2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FDR_TOBANTOMORROWASSERT3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FDR_TOBANTOMORROWASSERT4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FDR_TOBANTOMORROWASSERT5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')

FDR_TOBANTOMORROW_NO1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTOMORROW_NO2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTOMORROW_NO3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTOMORROW_NO4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTOMORROW_NO5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(5) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TODAY1= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(2) > select')
FDR_TODAY2= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(2) > select')
FDR_TODAY3= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(2) > select')
FDR_TODAY4= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(2) > select')
FDR_TODAY5= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(2) > select')

FDR_TOBANTODAY_YES1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTODAY_YES2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTODAY_YES3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTODAY_YES4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTODAY_YES5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.inactive')
FRD_TOBANTODAYASSERT1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FRD_TOBANTODAYASSERT2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FRD_TOBANTODAYASSERT3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FRD_TOBANTODAYASSERT4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FRD_TOBANTODAYASSERT5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(4) > div > label.btn.ng-pristine.ng-valid.active.btn-danger')
FDR_TOBANTODAY_NO1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(6) > div > label').contains('Yes')
FDR_TOBANTODAY_NO2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(6) > div > label').contains('Yes')
FDR_TOBANTODAY_NO3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(6) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTODAY_NO4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(6) > div > label.btn.ng-pristine.ng-valid.inactive')
FDR_TOBANTODAY_NO5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(6) > div > label.btn.ng-pristine.ng-valid.inactive')

FDR_ALL_TOBANTODAY_BTNS = () => cy.get('.btn-group-FireBanToday')
FDR_ALL_TOBANTOMORROW_BTNS = () => cy.get('.btn-group-FireBanTomorrow')

//FDR update sprint32//
FDR_TODAYplus1_1= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(3) > select')
FDR_TODAYplus1_2= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(3) > select')
FDR_TODAYplus1_3= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(3) > select')
FDR_TODAYplus1_4= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(3) > select')
FDR_TODAYplus1_5= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(3) > select')

FDR_TODAYplus2_1= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(4) > select')
FDR_TODAYplus2_2= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(4) > select')
FDR_TODAYplus2_3= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(4) > select')
FDR_TODAYplus2_4= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(4) > select')
FDR_TODAYplus2_5= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(4) > select')

FDR_TODAYplus3_1= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(5) > select')
FDR_TODAYplus3_2= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(5) > select')
FDR_TODAYplus3_3= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(5) > select')
FDR_TODAYplus3_4= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(5) > select')
FDR_TODAYplus3_5= ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(5) > select')

FDR_TOBANTODAYplus1_1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(7) > div > label').contains('Yes')
FDR_TOBANTODAYplus1_2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(7) > div > label').contains('Yes')
FDR_TOBANTODAYplus1_3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(7) > div > label').contains('Yes')
FDR_TOBANTODAYplus1_4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(7) > div > label').contains('Yes')
FDR_TOBANTODAYplus1_5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(7) > div > label').contains('Yes')

FDR_TOBANTODAYplus2_1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(8) > div > label').contains('Yes')
FDR_TOBANTODAYplus2_2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(8) > div > label').contains('Yes')
FDR_TOBANTODAYplus2_3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(8) > div > label').contains('Yes')
FDR_TOBANTODAYplus2_4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(8) > div > label').contains('Yes')
FDR_TOBANTODAYplus2_5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(8) > div > label').contains('Yes')

FDR_TOBANTODAYplus3_1 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(2) > div > div:nth-child(9) > div > label').contains('Yes')
FDR_TOBANTODAYplus3_2 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(3) > div > div:nth-child(9) > div > label').contains('Yes')
FDR_TOBANTODAYplus3_3 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(4) > div > div:nth-child(9) > div > label').contains('Yes')
FDR_TOBANTODAYplus3_4 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(5) > div > div:nth-child(9) > div > label').contains('Yes')
FDR_TOBANTODAYplus3_5 = ()=> cy.get('#article > div > div > firedangermap > div.container.ng-scope > div:nth-child(6) > div > div:nth-child(9) > div > label').contains('Yes')

FDR_ALL_TOBANTODAYplus1_BTNS = () => cy.get('.btn-group-FireBanTodayPlus1')
FDR_ALL_TOBANTODAYplus2_BTNS = () => cy.get('.btn-group-FireBanTodayPlus2')
FDR_ALL_TOBANTODAYplus3_BTNS = () => cy.get('.btn-group-FireBanTodayPlus3')

FDR_None_opt = () => cy.get('select.fdr-None')
FDR_Moderate_opt = () => cy.get('select.fdr-MODERATE')
FDR_High_opt = () => cy.get('select.fdr-HIGH')
FDR_Extreme_opt = () => cy.get('select.fdr-EXTREME')
FDR_Catastrophic_opt = () => cy.get('select.fdr-CATASTROPHIC')

FDR_Today_Info = () => cy.get('input[ng-model="district.DangerLevelToday"]')
FDR_TodayPlus1_Info = () => cy.get('input[ng-model="district.DangerLevelTodayPlus1"]')
FDR_TodayPlus2_Info = () => cy.get('input[ng-model="district.DangerLevelTodayPlus2"]')
FDR_TodayPlus3_Info = () => cy.get('input[ng-model="district.DangerLevelTodayPlus3"]')
}
export default FDRlocators

