class Mfulocators{
    VISIT_MFU_PAGE = () => cy.visit(`https://${Cypress.env('ICON_HOST_URL')}${'/PublicInformation/MajorFireUpdates'}`,{failOnStatusCode: false})
    PUBLIC_INFORMATION_TAB = ()=> cy.get('div#nav > ul:nth-child(1) > li:nth-child(5) > a')
    MAJOR_FIRE_UPDATE_MENU = ()=> cy.get('#nav > ul:nth-child(1) > li.dropdown.open > ul > li:nth-child(1) > a')
    MAJOR_FIRE_UPDATES_TITLE = ()=> cy.title().should('eq','Major Fire Updates')
    ADD_NEW_FIRE_UPDATE_BTN = ()=>  cy.get('#filters > div > div > div.span6 > div > a')
    SELECT_INCIDENT_BTN = ()=> cy.get('#btn_attachIncidents')
    SELECT_LGA_DROPDOWN = ()=> cy.get('#incidentPickerPage > div.picker > div')
    SELECTED_LGA_NAME = ()=> cy.get('#incidentPickerPage > div.picker > div > div.selectize-dropdown.single > div > div')
    INCIDENT_SELECT_CHECKBOX = ()=> cy.get('.incidentTable > tbody > :nth-child(1) > :nth-child(1) > .addIncident')
    MFU_NAME = ()=>  cy.get('#Name').type('Major fire update test')
    MGU_SUMMARY = ()=> cy.get('#Summary').type('Fire is getting bigger')
    MFU_BODY = ()=> cy.get('#Body')
    NEXT_BTTN_MFUINFOREQ_PAGE = ()=> cy.get('#generalNext')
    NEXT_BTTN_MFUWRNGMAP_PAGE = ()=> cy.get('#warningAreaEditNextButton > .hidden-phone')
    FACEBOOK_CHECKBOX = ()=> cy.get('#IsSendToFacebook')
    FACEBOOK_MESSAGE = ()=>  cy.get('#FacebookMessage').type('Fire is getting bigger')
    TWITTER_CHECKBOX = ()=>  cy.get('#IsSendToTwitter')
    TWITTER_MESSAGE = ()=>   cy.get('#TwitterMessage').type('Fire is getting bigger')
    SOCIAL_MEDIA_EDIT_NXTBTN = ()=> cy.get('#socialMedia > div.form-actions > div > div > a')
    PUBLISH_SPECIFICTIME_CHECKBOX = ()=> cy.get('#IsPublishNow_f')
    SELECTED_PUBLISHTIME_NXTBTN = ()=> cy.get('#publishing > .form-actions > :nth-child(1) > .pull-right > .btn')
    PUBLISH_BUTTON = ()=>  cy.get('#submit > .form-actions > :nth-child(1) > .pull-right > .btn')
    SELECT_LGAINCIDENT_DONE_BTN = ()=> cy.get('#btn_attachIncidentsDone').should('be.visible')
    NXT_BTTN_AFTER_DONE = ()=> cy.get('#attachedIncidentsPage > .form-actions > .pull-right > .btn')
    ASSERT_PUBLISHED = ()=>  cy.contains('Update Summary')
    SELECTED_INC_REISSUE = ()=> cy.get('#DataTables_Table_0 > tbody > tr:nth-child(1) > td:nth-child(2) > p > strong')
    REISUUE_BTTN = ()=> cy.get('#article > div.well.clearfix > div:nth-child(2) > a:nth-child(1)')
    RETIRE_BTN = () => cy.get('[href="#RetireModal"]')
    RETIRE_UPDATE_POPUP_BTN = () => cy.get('.btn-danger')
    PREVIEW_BUTTON = ()=> cy.get('#generalInformation > div.form-actions > div > div > button')
    PREVIEW_DIALOGUEBOX = ()=> cy.get('#WebsitePreviewModal > .modal-body > :nth-child(1)')
    CLOSE_PREVIEW = ()=> cy.get('#WebsitePreviewModal > .modal-footer > .btn')
    PUBLISH_NOW_CHECKBOX = ()=> cy.get('#IsPublishNow_t')
    NO_RETIRE_CHECKBOX = () => cy.get('#IsRetireSet_f')
    ONLY_MINE_CHECKBOX = () => cy.get('#IsMine')
    REISSUE_SUCCESS_ALERT = ()=> cy.get('.alert')
    
    MFU_SELECT_INCIDENTS_PAGE_FIRST_INCIDENT = () => cy.get('tbody > :nth-child(1) > :nth-child(3) > strong')
    MFU_SELECT_INCIDENTS_PAGE_SECOND_INCIDENT = () => cy.get('tbody > :nth-child(2) > :nth-child(3) > strong')

    MFU_INFORMATION_PREVIEW_BUTTON = ()=> cy.get('.pull-right > .btn-info')
    MFU_INFORMATION_NAME = () => cy.get('#Name')
    MFU_INFORMATION_SUMMARY = () => cy.get('#Summary')
    MFU_CURRENT_SITUATION = () => cy.get('#CurrentSituation')
    MFU_INFORMATION_ADVICE = () => cy.get('#Advice')
    MFU_INFORMATION_OTHER_INFO = () => cy.get('#OtherInformation')
    MFU_INFORMATION_NEXT_BUTTON = () => cy.get('#generalNext')
    MFU_INFORMATION_PUB_TO_WEBSITE_CHECKBOX =() => cy.get('#IsSendToPublicWebsite')

    MFU_PREVIEW_NAME = () => cy.get('#WebsitePreviewModal > .modal-header > #websiteTitle')
    MFU_PREVIEW_CURRENT_SITUATION = () => cy.get('#websiteCurrentSituation > p')
    MFU_PREVIEW_SUMMARY = () => cy.get('#websiteSummary > p')
    MFU_PREVIEW_ADVICE = () => cy.get('#websiteAdvice > p')
    MFU_PREVIEW_OTHER_INFO = () => cy.get('#websiteOtherInformation > p')
    
    
    MFU_WARNING_AREA_VALIDATE_BTN =() => cy.get('#warningAreaEditValidateButton')
    MFU_WARNING_AREA_NEXT_BTN = () => cy.get('#warningAreaEditNextButton')
    MFU_WARNING_AREA_VALIDATION_SUCCESS_ALERT = () => cy.get('[class="alert alert-success"]')
    MFU_WARNING_AREA_MAP = ()=> cy.get('#warningAreaEditMap_gc')
    MFU_WARNING_AREA_PENCIL = ()=> cy.get('.icon-pencil')
    MFU_WARNING_AREA_NEW_AREA_SYMBOL = () => cy.get('.itemSymbol')
    MFU_WARNING_AREA_NEW_AREA_SYMBOL_SELECTED = () => cy.get('[class="dojoxGridCell  dojoxGridCellFocus selectedItem"]')
    MFU_WARNING_AREA_EDIT_DELETE =  () => cy.get('#warningAreaEditDeleteButton')
    
    MFU_SOCIAL_NEXT_BTN = () => cy.get('#socialMediaEditNextButton')
    
    MFU_FEED_UPDATES_TABLE = () => cy.get('#DataTables_Table_0')
    MFU_FEED_UPDATES_TABLE_DATA_ROWS = () => cy.get('#DataTables_Table_0 > tbody > tr')
    MFU_FEED_UPDATES_TABLE_DATE_COLUMN = () => cy.get('#DataTables_Table_0 > tbody > tr > td > dl > dd > span')
    MFU_FEED_UPDATES_TABLE_RETIRE_COLUMN = () => cy.get('#DataTables_Table_0 > tbody > tr > td > dl > :nth-child(4)')
    MFU_FEED_UPDATES_TABLE_AUTHOR_NAME_COLUMN = () => cy.get('tr > :nth-child(3) > dl > dd')
    
    MFU_DETAILS_SUPERCEDE_LABEL = () =>cy.get(':nth-child(13) > :nth-child(3)')
    //updated element path after warning area maps activation
    MFU_DETAILS_SUPERCEDE_VALUE = () => cy.get('#article>dl:nth-Child(13)>dd:nth-child(4) > a:nth-child(1)')
    MFU_DETAILS_AUDIT_LABELS = () => cy.get('#article > :nth-child(13) >dt')
    MFU_DETAILS_PUB_SOCIAL_AUDIT_LABELS = () => cy.get('#article > .dl-horizontal > dt')
    
    
    MFU_DETAILS_SUPERCEDED_WARNING = () => cy.get('#article > .alert')
    MFU_DETAILS_RETIRED_WARNING = () => cy.get('#article > .alert')
    MFU_DETAILS_CONCURRENT_RETIRE_WARNING = () => cy.get('[class="alert alert-error"]').contains('Please check that you still want to retire this')
    }

    export default Mfulocators